In [31]:
import torch

In [32]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])

torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [33]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [34]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [35]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [36]:
X.sum()

tensor(66.)

In [37]:
a = torch.arange(12).reshape((3, 2, 2))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[[ 0,  1],
          [ 2,  3]],
 
         [[ 4,  5],
          [ 6,  7]],
 
         [[ 8,  9],
          [10, 11]]]),
 tensor([[0, 1]]))

In [38]:
a + b   #广播机制，⾸先，通过适当复制元素来扩展⼀个或两个数组，以便在转换之后，两个张量具有相同的形状。
        #其次，对生成的数组执行按元素操作

tensor([[[ 0,  2],
         [ 2,  4]],

        [[ 4,  6],
         [ 6,  8]],

        [[ 8, 10],
         [10, 12]]])

In [39]:
X[0:2]

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [40]:
X[:,0:2]=12
X

tensor([[12., 12.,  2.,  3.],
        [12., 12.,  6.,  7.],
        [12., 12., 10., 11.]])

In [41]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [42]:
Z = torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:] = X + Y
print('id(Z):',id(Z))

id(Z): 1513368403296
id(Z): 1513368403296


In [43]:
before = id(X)
X += Y
id(X) == before

True

In [44]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [45]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)