In [18]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [19]:
x.requires_grad_(True)
x.grad

In [20]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [21]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [22]:
x.grad == 4*x

tensor([True, True, True, True])

In [24]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
print(y)
y.backward()
x.grad

tensor(6., grad_fn=<SumBackward0>)


tensor([1., 1., 1., 1.])

In [25]:
# 对⾮标量调⽤backward需要传⼊⼀个gradient参数，该参数指定微分函数关于self的梯度。
# 在我们的例⼦中，我们只想求偏导数的和，所以传递⼀个1的梯度是合适的
x.grad.zero_()
y = x * x

In [26]:
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [30]:
x.grad.zero_()
y = x * x 
print(y)
u = y.detach()
print(u)
z = u * x 
print(z)

z.sum().backward()
print(x.grad)
x.grad == u

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)
tensor([0., 1., 4., 9.])
tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>)
tensor([0., 1., 4., 9.])


tensor([True, True, True, True])

In [31]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [32]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum()>0:
        c=b
    else:
        c=100*b
    return c

a = torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()

In [33]:
a.grad == d/a

tensor(True)